project_id = "lferxmdlttvitbuvekps"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-ai-charts]
verify_jwt = false

[functions.parse-uploaded-sheet]
verify_jwt = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[edge_runtime]
enabled = true
inspector_port = 8083
