
import { useEffect, useState, useRef } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { ChartData } from "@/contexts/ChartsContext";
import ChartRenderer from "@/components/panel/ChartRenderer";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const PlanilhaDetalhada = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { toast } = useToast();
  const [charts, setCharts] = useState<ChartData[]>([]);
  const chartsRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(false);

  const spreadsheetId = new URLSearchParams(location.search).get("id");

  const handleBack = () => {
    navigate("/dashboard/stats?type=home");
  };

  const fetchChartData = async () => {
    if (!spreadsheetId) return;
    
    console.log("🔍 PlanilhaDetalhada - Fetching chart data for spreadsheet:", spreadsheetId);
    setLoading(true);
    
    try {
      // Get spreadsheet data for AI chart generation
      const { data: sheetData, error: sheetError } = await supabase
        .from("sheets")
        .select("id")
        .eq("spreadsheet_id", spreadsheetId)
        .limit(1);

      if (sheetError || !sheetData?.length) {
        console.error("❌ PlanilhaDetalhada - Sheet not found:", sheetError);
        toast({ title: "Nenhuma aba encontrada na planilha", variant: "destructive" });
        setLoading(false);
        return;
      }

      const sheetId = sheetData[0].id;
      console.log("📄 PlanilhaDetalhada - Found sheet ID:", sheetId);

      const { data, error } = await supabase
        .from("spreadsheet_data")
        .select("*")
        .eq("sheet_id", sheetId);

      if (error) {
        console.error("❌ PlanilhaDetalhada - Error fetching data:", error);
        throw error;
      }

      if (!data || data.length === 0) {
        console.warn("⚠️ PlanilhaDetalhada - No data found");
        toast({ title: "Nenhum dado encontrado", variant: "destructive" });
        setLoading(false);
        return;
      }

      console.log("📊 PlanilhaDetalhada - Found spreadsheet data:", data.length, "rows");

      const rows = data.map((row: any) => ({
        row_index: row.row_index,
        column_index: row.column_index,
        column_name: row.column_name,
        value: row.cell_value,
      }));

      console.log("🤖 PlanilhaDetalhada - Calling AI function with data:", {
        totalRows: rows.length,
        sampleData: rows.slice(0, 3)
      });

      const aiResult = await supabase.functions.invoke("generate-ai-charts", {
        body: { data: rows }
      });

      console.log("📋 PlanilhaDetalhada - AI result:", aiResult);
      console.log("🔍 PlanilhaDetalhada - AI chartConfig:", aiResult.data?.chartConfig);

      if (aiResult.error) {
        console.error("❌ PlanilhaDetalhada - AI function error:", aiResult.error);
        toast({ title: "Erro ao gerar gráficos com IA", variant: "destructive" });
        setLoading(false);
        return;
      }

      if (!aiResult.data?.chartConfig || aiResult.data.chartConfig.length === 0) {
        console.log("⚠️ PlanilhaDetalhada - No charts generated by AI");
        toast({ title: "Nenhum gráfico gerado", description: "A IA não conseguiu gerar gráficos para esta planilha." });
        setCharts([]);
        setLoading(false);
        return;
      }

      // Convert Chart.js format to our standard format
      const convertedCharts = aiResult.data.chartConfig.map((chart: any, index: number) => {
        const title = chart.options?.plugins?.title?.text || 
                     chart.data?.datasets?.[0]?.label || 
                     `Gráfico ${index + 1}`;

        const labels = chart.data?.labels || [];
        const dataset = chart.data?.datasets?.[0];
        const values = dataset?.data || [];

        const standardData = labels.map((label: string, idx: number) => ({
          label: String(label || `Item ${idx + 1}`),
          value: Number(values[idx]) || 0
        })).filter((item: any) => item.label && (item.value >= 0 || !isNaN(item.value)));

        return {
          type: chart.type || 'bar',
          title: title,
          data: standardData
        };
      }).filter((chart: any) => chart.data.length > 0);

      console.log("✅ PlanilhaDetalhada - Charts converted:", convertedCharts.length);
      console.log("✅ CONFIRMED: Charts rendered in PlanilhaDetalhada are from Gemini AI!");
      setCharts(convertedCharts);

    } catch (err) {
      console.error("❌ PlanilhaDetalhada - Unexpected error:", err);
      toast({ title: "Erro", description: "Erro ao buscar dados para gráficos." });
    } finally {
      setLoading(false);
    }
  };

  const downloadAsPDF = async () => {
    if (!chartsRef.current) return;
    try {
      const canvas = await html2canvas(chartsRef.current);
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF();
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save("relatorio-graficos.pdf");
    } catch (error) {
      console.error("Error downloading PDF:", error);
    }
  };

  useEffect(() => {
    fetchChartData();
  }, [spreadsheetId]);

  if (loading) {
    return (
      <div className="p-4 space-y-6">
        <div className="flex justify-between items-center">
          <Button onClick={handleBack}>← Voltar</Button>
        </div>
        <div className="text-center py-8">
          <div className="animate-pulse space-y-4">
            <div className="w-16 h-16 bg-primary/20 rounded-full mx-auto animate-bounce"></div>
            <p className="text-muted-foreground">Gerando gráficos...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 space-y-6">
      <div className="flex justify-between items-center">
        <Button onClick={handleBack}>← Voltar</Button>
        {charts.length > 0 && (
          <Button variant="outline" onClick={downloadAsPDF}>Baixar PDF</Button>
        )}
      </div>

      <h2 className="text-2xl font-bold">Detalhes da Planilha</h2>

      {charts.length === 0 ? (
        <div className="text-center py-16 space-y-4">
          <div className="w-24 h-24 mx-auto bg-muted rounded-full flex items-center justify-center">
            <svg className="w-12 h-12 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </div>
          <h3 className="text-xl font-medium text-muted-foreground">
            Nenhum gráfico disponível
          </h3>
          <p className="text-muted-foreground">
            Não foi possível gerar gráficos para esta planilha
          </p>
        </div>
      ) : (
        <div ref={chartsRef} className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {charts.map((chart, i) => {
            console.log(`📊 PlanilhaDetalhada - Rendering chart ${i}:`, chart);
            return (
              <ChartRenderer key={i} chart={chart} />
            );
          })}
        </div>
      )}
    </div>
  );
};

export default PlanilhaDetalhada;
