// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lferxmdlttvitbuvekps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXJ4bWRsdHR2aXRidXZla3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDQ4MDAsImV4cCI6MjA2NzU4MDgwMH0.1XThEsS3vtjX3CW1A55TFpr1WRmj_0T798QiQbFMulo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});